import Document, { Html, Head, Main, NextScript } from "next/document";
import handleAuthSSR from "../libs/auth";

export default class MyAppDocument extends Document {
  static async getInitialProps(ctx: any) {
    await handleAuthSSR(ctx);
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link
            href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;700&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
          <footer className="w-100 text-center mt-1">
            <span className="text-muted">Created by Long VPV</span>
          </footer>
        </body>
      </Html>
    );
  }
}
