language: node_js
node_js:
  - 8.6.0

cache:
  directories:
    - node_modules

install:
  - npm install
  - cd client
  - npm install
  - cd ..
  - npm install -g jest

jobs:
  include:
    - stage: Produce Coverage
      node_js: 8.6.0
      script:
        - npm run lint
        - npm run test:coverage && cat ./client/coverage/jest/lcov.info | ./client/node_modules/coveralls/bin/coveralls.js

sudo: false
